### ISSUE TITLE
Cannot install Cling kernel into a virtualenv Jupyter application

### ISSUE THREAD

**Issue by ulf1** [root-mirror/cling#1]
Hello, i hope someone can help. 

I installed Cling using simply this script

https://raw.github.com/karies/cling-all-in-one/master/clone.sh

I also added Cling to my PATH variable (in .bashrc), and can run stuff like this

`cling '#include <stdio.h>' 'printf("Hello World!\n")'`

Next I open my activate my virtualenv with Python 3.5.0 where Jupyter is installed (There is no Jupyter in my operating systems python3). There is no problem with Jupyter/Python3 within a virtualenv bcoz I am using it everyday. There is also not a problem with PATH and cling within the virtualenv (I can call call "cling" within the virtualenv).

If i am trying to install cling in jupyter
`source /locationofmyvirtualenv/bin/activate`
`jupyter kernelspec install cling`

I get the following error message

<pre>
...
(venv-3.5.0)username@hostname:~$ jupyter kernelspec install cling
Traceback (most recent call last):
  File "/locationofmyvirtualenv/bin/jupyter-kernelspec", line 11, in <module>
    sys.exit(KernelSpecApp.launch_instance())
  File "/locationofmyvirtualenv/lib/python3.5/site-packages/traitlets/config/application.py", line 589, in launch_instance
    app.start()
  File "/locationofmyvirtualenv/lib/python3.5/site-packages/jupyter_client/kernelspecapp.py", line 209, in start
    return self.subapp.start()
  File "/locationofmyvirtualenv/lib/python3.5/site-packages/jupyter_client/kernelspecapp.py", line 138, in start
    replace=self.replace,
  File "/locationofmyvirtualenv/lib/python3.5/site-packages/jupyter_client/kernelspec.py", line 208, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/locationofmyvirtualenv/lib/python3.5/shutil.py", line 303, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: 'cling'
... 
</pre>

**Comment by karies** [comment]
Can you add cling to $PATH before starting up jupyter?

**Comment by mjanv** [comment]
I've run into the same issue as @ulf1 on this installation : Ubuntu 14.04 in a VM, Python3.5 via Anaconda (jupyter v4.0.6 and jupyter notebook v4.1.0), no virtualenv, cling installed (at `` /usr/local/bin/cling ``) and tested.

By adding a symlink ``./cling -> /usr/local/bin/cling``, I overpass the previous error (similar to @ulf1's one) to get a new one :
```
vagrant@VMSandbox:~$ jupyter kernelspec install cling
Traceback (most recent call last):
  File "/home/vagrant/anaconda3/bin/jupyter-kernelspec", line 8, in <module>
    main()
  File "/home/vagrant/anaconda3/bin/jupyter-kernelspec", line 5, in main
    KernelSpecApp.launch_instance()
  File "/home/vagrant/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 592, in launch_instance
    app.start()
  File "/home/vagrant/anaconda3/lib/python3.5/site-packages/jupyter_client/kernelspecapp.py", line 209, in start
    return self.subapp.start()
  File "/home/vagrant/anaconda3/lib/python3.5/site-packages/jupyter_client/kernelspecapp.py", line 138, in start
    replace=self.replace,
  File "/home/vagrant/anaconda3/lib/python3.5/site-packages/jupyter_client/kernelspec.py", line 208, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/home/vagrant/anaconda3/lib/python3.5/shutil.py", line 303, in copytree
    names = os.listdir(src)
NotADirectoryError: [Errno 20] Not a directory: 'cling'
```
Any ideas ?

**Comment by karies** [comment]
Yup, indeed - the doc was not clear. I /believe/ that this is the correct procedure:
```
To install the kernel with sources in cling/src:

    cd cling/src/tools/Jupyter/kernel/
     pip install -e .
     # register the kernelspec:
     jupyter kernelspec install [--user] cling
```
Could you confirm?

**Comment by mjanv** [comment]
Using your commands :
```
vagrant@VMSandbox:~/src/tools/cling/tools/Jupyter/kernel$ pip install -e .
Obtaining file:///home/vagrant/src/tools/cling/tools/Jupyter/kernel
Requirement already up-to-date: ipykernel in /home/vagrant/anaconda3/lib/python3.5/site-packages (from clingkernel==0.0.1)
Requirement already up-to-date: traitlets in /home/vagrant/anaconda3/lib/python3.5/site-packages (from clingkernel==0.0.1)
Installing collected packages: clingkernel
  Running setup.py develop for clingkernel
Successfully installed clingkernel-0.0.1
vagrant@VMSandbox:~/src/tools/cling/tools/Jupyter/kernel$ jupyter kernelspec install --user cling
[InstallKernelSpec] Installed kernelspec cling in /home/vagrant/.local/share/jupyter/kernels/cling
```
which somehow succeed to install the kernel. It appears in the list of available notebooks in Jupyter (yeah !) listed as C++, but the kernel keeps crashing because of this error (a dylib missing):
```
[I 09:15:52.046 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 1f5e9824-096e-453d-b987-0baad4d819af restarted
Traceback (most recent call last):
  File "/home/vagrant/anaconda3/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/vagrant/src/tools/cling/tools/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/home/vagrant/src/tools/cling/tools/Jupyter/kernel/clingkernel.py", line 278, in main
    ClingKernelApp.launch_instance()
  File "/home/vagrant/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-121>", line 2, in initialize
  File "/home/vagrant/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/vagrant/anaconda3/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 384, in initialize
    self.init_kernel()
  File "/home/vagrant/anaconda3/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 323, in init_kernel
    user_ns=self.user_ns,
  File "/home/vagrant/anaconda3/lib/python3.5/site-packages/traitlets/config/configurable.py", line 404, in instance
    inst = cls(*args, **kwargs)
  File "/home/vagrant/src/tools/cling/tools/Jupyter/kernel/clingkernel.py", line 77, in __init__
    self.libclingJupyter = ctypes.CDLL(clingInstDir + "/lib/libclingJupyter.dylib", mode = ctypes.RTLD_GLOBAL)
  File "/home/vagrant/anaconda3/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libclingJupyter.dylib: cannot open shared object file: No such file or directory
```

We're running in a new problem which was not the primer purpose of the issue. I'd like to know if @ulf1 succeed to overcome the error as well.

**Comment by karies** [comment]
Please start jupyter with cling in the $PATH. I.e. is /usr/local/bin in your $PATH? I will try to improve the error message if that's the case :-)

If it is - do you have something here: /usr/local/lib/libclingJupyter.* In my case, that library does get installed...

**Comment by mjanv** [comment]
Yes, i have already checked that cling was in the PATH (`/home/vagrant/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`) through `/usr/local/bin`

I did not find any libclingJupyter on my system. Any steps, options, I missed ?
```
vagrant@VMSandbox:/code$ ls /usr/local/lib/
BugpointPasses.so                 libLLVMMCDisassembler.a
clang                             libLLVMMCJIT.a
libclang.a                        libLLVMMCParser.a
libclangAnalysis.a                libLLVMMipsAsmParser.a
libclangARCMigrate.a              libLLVMMipsAsmPrinter.a
libclangAST.a                     libLLVMMipsCodeGen.a
libclangASTMatchers.a             libLLVMMipsDesc.a
libclangBasic.a                   libLLVMMipsDisassembler.a
libclangCodeGen.a                 libLLVMMipsInfo.a
libclangDriver.a                  libLLVMMSP430AsmPrinter.a
libclangDynamicASTMatchers.a      libLLVMMSP430CodeGen.a
libclangEdit.a                    libLLVMMSP430Desc.a
libclangFormat.a                  libLLVMMSP430Info.a
libclangFrontend.a                libLLVMNVPTXAsmPrinter.a
libclangFrontendTool.a            libLLVMNVPTXCodeGen.a
libclangIndex.a                   libLLVMNVPTXDesc.a
libclangLex.a                     libLLVMNVPTXInfo.a
libclangParse.a                   libLLVMObjCARCOpts.a
libclangRewrite.a                 libLLVMObject.a
libclangRewriteFrontend.a         libLLVMOption.a
libclangSema.a                    libLLVMOrcJIT.a
libclangSerialization.a           libLLVMPowerPCAsmParser.a
libclang.so                       libLLVMPowerPCAsmPrinter.a
libclangStaticAnalyzerCheckers.a  libLLVMPowerPCCodeGen.a
libclangStaticAnalyzerCore.a      libLLVMPowerPCDesc.a
libclangStaticAnalyzerFrontend.a  libLLVMPowerPCDisassembler.a
libclangTooling.a                 libLLVMPowerPCInfo.a
libclangToolingCore.a             libLLVMProfileData.a
libclingInterpreter.a             libLLVMR600AsmParser.a
libclingMetaProcessor.a           libLLVMR600AsmPrinter.a
libclingUITextInput.a             libLLVMR600CodeGen.a
libclingUserInterface.a           libLLVMR600Desc.a
libclingUtils.a                   libLLVMR600Info.a
libLLVMAArch64AsmParser.a         libLLVMRuntimeDyld.a
libLLVMAArch64AsmPrinter.a        libLLVMScalarOpts.a
libLLVMAArch64CodeGen.a           libLLVMSelectionDAG.a
libLLVMAArch64Desc.a              libLLVMSparcAsmParser.a
libLLVMAArch64Disassembler.a      libLLVMSparcAsmPrinter.a
libLLVMAArch64Info.a              libLLVMSparcCodeGen.a
libLLVMAArch64Utils.a             libLLVMSparcDesc.a
libLLVMAnalysis.a                 libLLVMSparcDisassembler.a
libLLVMARMAsmParser.a             libLLVMSparcInfo.a
libLLVMARMAsmPrinter.a            libLLVMSupport.a
libLLVMARMCodeGen.a               libLLVMSystemZAsmParser.a
libLLVMARMDesc.a                  libLLVMSystemZAsmPrinter.a
libLLVMARMDisassembler.a          libLLVMSystemZCodeGen.a
libLLVMARMInfo.a                  libLLVMSystemZDesc.a
libLLVMAsmParser.a                libLLVMSystemZDisassembler.a
libLLVMAsmPrinter.a               libLLVMSystemZInfo.a
libLLVMBitReader.a                libLLVMTableGen.a
libLLVMBitWriter.a                libLLVMTarget.a
libLLVMCodeGen.a                  libLLVMTransformUtils.a
libLLVMCore.a                     libLLVMVectorize.a
libLLVMCppBackendCodeGen.a        libLLVMX86AsmParser.a
libLLVMCppBackendInfo.a           libLLVMX86AsmPrinter.a
libLLVMDebugInfoDWARF.a           libLLVMX86CodeGen.a
libLLVMExecutionEngine.a          libLLVMX86Desc.a
libLLVMHexagonCodeGen.a           libLLVMX86Disassembler.a
libLLVMHexagonDesc.a              libLLVMX86Info.a
libLLVMHexagonDisassembler.a      libLLVMX86Utils.a
libLLVMHexagonInfo.a              libLLVMXCoreAsmPrinter.a
libLLVMInstCombine.a              libLLVMXCoreCodeGen.a
libLLVMInstrumentation.a          libLLVMXCoreDesc.a
libLLVMInterpreter.a              libLLVMXCoreDisassembler.a
libLLVMipa.a                      libLLVMXCoreInfo.a
libLLVMipo.a                      libLTO.a
libLLVMIRReader.a                 libLTO.so
libLLVMLineEditor.a               LLVMHello.so
libLLVMLinker.a                   python2.7
libLLVMLTO.a                      python3.4
libLLVMMC.a                       site_ruby
```

**Comment by karies** [comment]
Understood - libclingJupyter is only build using CMake. Given that llvm has removed autoconf I hace switched clone.sh to CMake, too.

Please rm -rf obj and re-run ./clone.sh after pulling it. Let me know if you still see issues.

**Comment by lenck** [comment]
I think this is a bug in the source code. Does (this)[https://github.com/root-mirror/cling/blob/master/tools/Jupyter/kernel/clingkernel.py#L77] means that the cling kernel is supported only for Mac OSX when it has hard-coded `*.dylib` library loading?

**Comment by karies** [comment]
Ouch. That should be fixed in the current HEAD. Could you give it a spin?

Thanks for reporting!

**Comment by ObiWahn** [comment]
Hi i am trying to install cling to a docker container and i run in smilar problems. I have configured cling with --prefix=/usr/local. i am ab bit confused about: `To install the kernel with sources in src/tools/cling:`
is that a prefix do you really mean to install to the source tree?

here a part of my docker log

```
Step 17 : RUN ls -lisa /usr/local/bin
 ---> Running in 89abc70b876b
total 3957804
 10916322      4 drwxrwsr-x  2 root staff      4096 Feb 15 07:40 .
 10841467      4 drwxrwsr-x 11 root staff      4096 Feb 15 07:40 ..
128320570   3680 -rwxr-xr-x  2 root staff   3766800 Feb 15 07:34 FileCheck
128320571 158856 -rwxr-xr-x  2 root staff 162667632 Feb 15 07:34 bugpoint
128320572    172 -rwxr-xr-x  2 root staff    173960 Feb 15 07:34 c-index-test
128320573 881388 -rwxr-xr-x  2 root staff 902535024 Feb 15 07:34 clang
130417228      0 lrwxrwxrwx  1 root staff         5 Feb 15 07:34 clang++ -> clang
128320575 372360 -rwxr-xr-x  2 root staff 381289744 Feb 15 07:34 clang-check
128320576  24032 -rwxr-xr-x  2 root staff  24608112 Feb 15 07:34 clang-format
128320577  10056 -rwxr-xr-x  2 root staff  10296048 Feb 15 07:34 clang-tblgen
128320578 584176 -rwxr-xr-x  2 root staff 598188352 Feb 15 07:36 cling
130417229      4 lrwxrwxrwx  1 root staff        71 Feb 13 19:19 configurable-http-proxy -> ../lib/node_modules/configurable-ht
tp-proxy/bin/configurable-http-proxy
128320579     12 -rwxr-xr-x  2 root staff     10512 Feb 15 07:34 count
128320580 335896 -rwxr-xr-x  2 root staff 343950448 Feb 15 07:34 llc
128320581 185036 -rwxr-xr-x  2 root staff 189469536 Feb 15 07:34 lli
128320582   3184 -rwxr-xr-x  2 root staff   3258360 Feb 15 07:34 lli-child-target
128320583  94312 -rwxr-xr-x  2 root staff  96571808 Feb 15 07:34 llvm-ar
128320584  26360 -rwxr-xr-x  2 root staff  26991696 Feb 15 07:34 llvm-as
128320585   3620 -rwxr-xr-x  2 root staff   3703464 Feb 15 07:34 llvm-bcanalyzer
128320586   2608 -rwxr-xr-x  2 root staff   2669080 Feb 15 07:34 llvm-config
128320587  30824 -rwxr-xr-x  2 root staff  31559952 Feb 15 07:34 llvm-cov
128320588  25292 -rwxr-xr-x  2 root staff  25898704 Feb 15 07:34 llvm-diff
128320589  22152 -rwxr-xr-x  2 root staff  22680880 Feb 15 07:34 llvm-dis
128320590  31384 -rwxr-xr-x  2 root staff  32136552 Feb 15 07:34 llvm-dsymutil
128320591  30520 -rwxr-xr-x  2 root staff  31250456 Feb 15 07:34 llvm-dwarfdump
128320592  34880 -rwxr-xr-x  2 root staff  35715608 Feb 15 07:34 llvm-extract
128320593  29940 -rwxr-xr-x  2 root staff  30657808 Feb 15 07:34 llvm-link
128320594  95972 -rwxr-xr-x  2 root staff  98271584 Feb 15 07:34 llvm-mc
128320595   3112 -rwxr-xr-x  2 root staff   3185544 Feb 15 07:34 llvm-mcmarkup
128320596  94240 -rwxr-xr-x  2 root staff  96498304 Feb 15 07:34 llvm-nm
128320597 104720 -rwxr-xr-x  2 root staff 107233024 Feb 15 07:34 llvm-objdump
128320598  18344 -rwxr-xr-x  2 root staff  18784128 Feb 15 07:34 llvm-profdata
130417230      0 lrwxrwxrwx  1 root staff         7 Feb 15 07:34 llvm-ranlib -> llvm-ar
128320600  36044 -rwxr-xr-x  2 root staff  36906032 Feb 15 07:34 llvm-readobj
128320601  68476 -rwxr-xr-x  2 root staff  70116312 Feb 15 07:34 llvm-rtdyld
128320602  32116 -rwxr-xr-x  2 root staff  32883424 Feb 15 07:34 llvm-size
128320603  23500 -rwxr-xr-x  2 root staff  24060896 Feb 15 07:34 llvm-stress
128320604  36152 -rwxr-xr-x  2 root staff  37016616 Feb 15 07:34 llvm-symbolizer
128320605  30804 -rwxr-xr-x  2 root staff  31540032 Feb 15 07:34 llvm-tblgen
128320606  34356 -rwxr-xr-x  2 root staff  35177976 Feb 15 07:34 llvm-vtabledump
128320607  31824 -rwxr-xr-x  2 root staff  32586496 Feb 15 07:34 macho-dump
128320608   2440 -rwxr-xr-x  2 root staff   2498344 Feb 15 07:34 not
128320609  34004 -rwxr-xr-x  2 root staff  34819160 Feb 15 07:34 obj2yaml
128320610 385896 -rwxr-xr-x  2 root staff 395149808 Feb 15 07:34 opt
128320611  28796 -rwxr-xr-x  2 root staff  29483520 Feb 15 07:34 verify-uselistorder
128320612   6256 -rwxr-xr-x  2 root staff   6405688 Feb 15 07:34 yaml2obj
 ---> 6c4325bfecb9
Removing intermediate container 89abc70b876b
Step 18 : RUN ls -lisa /usr/local/sbin
 ---> Running in 6d8f7881c28b
total 8
11183299 4 drwxrwsr-x  2 root staff 4096 Jan 25 15:18 .
11183298 4 drwxrwsr-x 11 root staff 4096 Feb 15 07:40 ..
 ---> 1c4e4903ed97
Removing intermediate container 6d8f7881c28b
Step 19 : RUN jupyter kernelspec install cling
 ---> Running in 7fd8ca918b30
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-kernelspec", line 8, in <module>
    main()
  File "/opt/conda/bin/jupyter-kernelspec", line 5, in main
    KernelSpecApp.launch_instance()
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 589, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.5/site-packages/jupyter_client/kernelspecapp.py", line 209, in start
    return self.subapp.start()
  File "/opt/conda/lib/python3.5/site-packages/jupyter_client/kernelspecapp.py", line 138, in start
    replace=self.replace,
  File "/opt/conda/lib/python3.5/site-packages/jupyter_client/kernelspec.py", line 208, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/opt/conda/lib/python3.5/shutil.py", line 303, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: 'cling'
The command '/bin/sh -c jupyter kernelspec install cling' returned a non-zero code: 1
```

**Comment by ObiWahn** [comment]
install
--------
```
root@80692fd5f9da:/srv/cling-src/tools/cling/tools/Jupyter/kernel# pip install -e .                                                    
Obtaining file:///srv/cling-src/tools/cling/tools/Jupyter/kernel
Requirement already satisfied (use --upgrade to upgrade): ipykernel in /opt/conda/lib/python3.5/site-packages (from clingkernel==0.0.1)
Requirement already satisfied (use --upgrade to upgrade): traitlets in /opt/conda/lib/python3.5/site-packages (from clingkernel==0.0.1)
Installing collected packages: clingkernel
  Running setup.py develop for clingkernel
Successfully installed clingkernel
root@80692fd5f9da:/srv/cling-src/tools/cling/tools/Jupyter/kernel# jupyter kernelspec install cling
[InstallKernelSpec] Installed kernelspec cling in /usr/local/share/jupyter/kernels/cling
```

error
------

```
I 2016-02-15 19:42:10.054 obi handlers:170] Creating new notebook in 
[I 2016-02-15 19:42:10.063 obi sign:178] Writing notebook-signing key to /home/obi/.local/share/jupyter/notebook_secret
[W 2016-02-15 19:42:11.080 obi log:47] 404 GET /jupyter/user/obi/nbextensions/widgets/notebook/js/extension.js?v=20160215194205 (172.17.42.1) 7.28ms referer=http://localhost:8000/jupyter/user/obi/notebooks/Untitled.ipynb?kernel_name=cling
[I 2016-02-15 19:42:11.255 obi kernelmanager:89] Kernel started: e6e00760-b82a-4c8e-9f78-b12b1a120842
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/srv/cling-src/tools/cling/tools/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/srv/cling-src/tools/cling/tools/Jupyter/kernel/clingkernel.py", line 287, in main
    ClingKernelApp.launch_instance()
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-122>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 384, in initialize
    self.init_kernel()
  File "/opt/conda/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 323, in init_kernel
    user_ns=self.user_ns,
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/configurable.py", line 404, in instance
    inst = cls(*args, **kwargs)
  File "/srv/cling-src/tools/cling/tools/Jupyter/kernel/clingkernel.py", line 84, in __init__
    if not self.libclingJupyter:
AttributeError: 'ClingKernel' object has no attribute 'libclingJupyter'
[I 2016-02-15 19:42:14.257 obi restarter:103] KernelRestarter: restarting kernel (1/5)
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/srv/cling-src/tools/cling/tools/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/srv/cling-src/tools/cling/tools/Jupyter/kernel/clingkernel.py", line 287, in main
    ClingKernelApp.launch_instance()
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-122>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 384, in initialize
    self.init_kernel()
  File "/opt/conda/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 323, in init_kernel
    user_ns=self.user_ns,
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/configurable.py", line 404, in instance
    inst = cls(*args, **kwargs)
  File "/srv/cling-src/tools/cling/tools/Jupyter/kernel/clingkernel.py", line 84, in __init__
    if not self.libclingJupyter:
AttributeError: 'ClingKernel' object has no attribute 'libclingJupyter'
[I 2016-02-15 19:42:17.266 obi restarter:103] KernelRestarter: restarting kernel (2/5)
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/srv/cling-src/tools/cling/tools/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/srv/cling-src/tools/cling/tools/Jupyter/kernel/clingkernel.py", line 287, in main
    ClingKernelApp.launch_instance()
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-122>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 384, in initialize
    self.init_kernel()
  File "/opt/conda/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 323, in init_kernel
    user_ns=self.user_ns,
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/configurable.py", line 404, in instance
    inst = cls(*args, **kwargs)
  File "/srv/cling-src/tools/cling/tools/Jupyter/kernel/clingkernel.py", line 84, in __init__
    if not self.libclingJupyter:
AttributeError: 'ClingKernel' object has no attribute 'libclingJupyter'
[I 2016-02-15 19:42:20.274 obi restarter:103] KernelRestarter: restarting kernel (3/5)
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/srv/cling-src/tools/cling/tools/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/srv/cling-src/tools/cling/tools/Jupyter/kernel/clingkernel.py", line 287, in main
    ClingKernelApp.launch_instance()
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-122>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 384, in initialize
    self.init_kernel()
  File "/opt/conda/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 323, in init_kernel
    user_ns=self.user_ns,
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/configurable.py", line 404, in instance
    inst = cls(*args, **kwargs)
  File "/srv/cling-src/tools/cling/tools/Jupyter/kernel/clingkernel.py", line 84, in __init__
    if not self.libclingJupyter:
AttributeError: 'ClingKernel' object has no attribute 'libclingJupyter'
[W 2016-02-15 19:42:21.462 obi handlers:201] Timeout waiting for kernel_info reply from e6e00760-b82a-4c8e-9f78-b12b1a120842
[I 2016-02-15 19:42:23.282 obi restarter:103] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel e6e00760-b82a-4c8e-9f78-b12b1a120842 restarted
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/srv/cling-src/tools/cling/tools/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/srv/cling-src/tools/cling/tools/Jupyter/kernel/clingkernel.py", line 287, in main
    ClingKernelApp.launch_instance()
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-122>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 384, in initialize
    self.init_kernel()
  File "/opt/conda/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 323, in init_kernel
    user_ns=self.user_ns,
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/configurable.py", line 404, in instance
    inst = cls(*args, **kwargs)
  File "/srv/cling-src/tools/cling/tools/Jupyter/kernel/clingkernel.py", line 84, in __init__
    if not self.libclingJupyter:
AttributeError: 'ClingKernel' object has no attribute 'libclingJupyter'
[W 2016-02-15 19:42:26.290 obi restarter:95] KernelRestarter: restart failed
[W 2016-02-15 19:42:26.290 obi kernelmanager:54] Kernel e6e00760-b82a-4c8e-9f78-b12b1a120842 died, removing from map.
ERROR:root:kernel e6e00760-b82a-4c8e-9f78-b12b1a120842 restarted failed!
[W 2016-02-15 19:42:26.328 obi handlers:463] Kernel deleted before session
[W 2016-02-15 19:42:26.329 obi log:47] 410 DELETE /jupyter/user/obi/api/sessions/7f85a032-6547-4f4f-b307-3b67549657d1 (172.17.42.1) 1.12ms referer=http://localhost:8000/jupyter/user/obi/notebooks/Untitled.ipynb?kernel_name=cling
[I 2016-02-15 19:44:11.267 obi handlers:179] Saving file at /Untitled.ipynb
```

**Comment by ulf1** [comment]
sorry for my late reply
<pre>
source $locationofmyvirtualenv/bin/activate
cd $locationofcling/src/tools/cling/tools/Jupyter/kernel/
pip install -e .
jupyter kernelspec install --user cling
</pre>
this works.

now i got the "libclingJupyter.dylib" error.
(I added cling to PATH)

**Comment by jhidding** [comment]
On Debian testing, somehow the libclingJupiter.so (or any other llvm installed .so file) doesn't have the executable flag set during install. This is what the Python module is checking using os.access(..., os.X_OK) on line 79 of clingkernel.py. For me doing

    > for f in *.so; do chmod +x $f; done

in the $clingpath/lib directory fixes the issue.

**Comment by ObiWahn** [comment]
I had fixed that in a pull request. The .so does not need the x flag. Fixing it like this is wrong. The python code should rather just check existence of a file.

Regards

On March 18, 2016 9:29:25 PM GMT+01:00, Johannes Hidding <notifications@github.com> wrote:
>On Debian testing, somehow the libclingJupiter.so (or any other llvm
>installed .so file) doesn't have the executable flag set during
>install. This is what the Python module is checking using
>os.access(..., os.X_OK) on line 79 of clingkernel.py. For me doing
>
>    > for f in *.so; do chmod +x $f; done
>
>in the $clingpath/lib directory fixes the issue.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/root-mirror/cling/issues/1#issuecomment-198529214

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by EHadoux** [comment]
Hello, I am also fighting to make the kernel work.
Alongside all the error above I have one more which is:
```
[I 15:46:43.460 NotebookApp] KernelRestarter: restarting kernel (1/5)
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ehadoux/Softwares/cling_2016-04-07_ubuntu14/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/home/ehadoux/Softwares/cling_2016-04-07_ubuntu14/kernel/clingkernel.py", line 287, in main
    ClingKernelApp.launch_instance()
  File "/home/ehadoux/.local/lib/python2.7/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-122>", line 2, in initialize
  File "/home/ehadoux/.local/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/ehadoux/.local/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 421, in initialize
    self.init_kernel()
  File "/home/ehadoux/.local/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 360, in init_kernel
    user_ns=self.user_ns,
  File "/home/ehadoux/.local/lib/python2.7/site-packages/traitlets/config/configurable.py", line 405, in instance
    inst = cls(*args, **kwargs)
  File "/home/ehadoux/Softwares/cling_2016-04-07_ubuntu14/kernel/clingkernel.py", line 70, in __init__
    whichCling = shutil.which('cling')
AttributeError: 'module' object has no attribute 'which'
```

Moreover, it does not seem possible to install the kernel using the binary package, only using the source from git, which is sad and constraining.

Thank you!

P.S.: I use the version of today.

**Comment by hellpanderrr** [comment]
@EHadoux 
<b>which</b> was added in Python3
A possible solution (which I used):
```python
        try:
        	whichCling = shutil.which('cling')
        except AttributeError:
        	from distutils.spawn import find_executable
        	whichCling = find_executable('cling') 
```

**Comment by karies** [comment]
Hi @EHadoux 
> Moreover, it does not seem possible to install the kernel using the binary package, only using the source from git, which is sad and constraining.

I totally agree. Would you be able to come up with a patch?

**Comment by karies** [comment]
@hellpanderrr your patch from https://github.com/root-mirror/cling/issues/1#issuecomment-207091090 is in. Thanks!

**Comment by karies** [comment]
We have Issue #7 for the binary missing the Jupyter kernel. I believe the remaining issues are addressed. Closing...

Thanks to everyone for reporting, and esp to @ObiWahn for the PR!

**Comment by EHadoux** [comment]
Hi, 

I'm not quite sure what to do. I mean, isn't it enough to just have the ```tools``` directory into the tar?

**Comment by karies** [comment]
@EHadoux - let's continue the discussion in #7 but what's missing is the install step for the kernel's python code.
