### ISSUE TITLE
compilation error:DeclCollector.cpp:201:19: error: no member named   'HandleInvalidTagDeclDefinition' in 'clang::ASTConsumer'

### ISSUE THREAD

**Issue by AlexLuya** [root-mirror/cling#14]
**"python cpt.py -c" gives me error:**
````bash
Cling Packaging Tool (CPT)
Arguments vector: ['cpt.py', '-c']

╔══════════════════════════════════════════════════════════════════════════════╗
║ cling (x86_64)                               Tue, 19 Apr 2016 18:32:48 +0800 ║
╚══════════════════════════════════════════════════════════════════════════════╝
Thread Model: POSIX
Operating System: Linux
Distribution: Ubuntu
Release: trusty
Revision: 14.04
Architecture: x86_64

┌──────────────────────────────────────────────────────────────────────────────┐
│ Check availability of required softwares                                     │
└──────────────────────────────────────────────────────────────────────────────┘
git                 [OK]                          
gcc                 [OK]                          
g++                 [OK]                          
debhelper           [OK]                          
subprocess.CalledProcessError: Command 'dpkg-query -W -f='${Status}' devscripts 2>/dev/null | grep -c 'ok installed'' returned non-zero exit status 1



┌──────────────────────────────────────────────────────────────────────────────┐
│ Clean up                                                                     │
└──────────────────────────────────────────────────────────────────────────────┘
Remove directory: /tmp/cling-obj/
Traceback (most recent call last):
  File "cpt.py", line 1390, in <module>
    check_ubuntu('devscripts')
  File "cpt.py", line 452, in check_ubuntu
    elif exec_subprocess_check_output("dpkg-query -W -f='${Status}' %s 2>/dev/null | grep -c 'ok installed'"%(pkg), '/').strip() == '0':
  File "cpt.py", line 89, in exec_subprocess_check_output
    return out
UnboundLocalError: local variable 'out' referenced before assignment
````

**and I ignored this and run,**
````bash
python cpt.py --current-dev deb
````
**After a long long time compilation,I got:**

````bash
llvm[4]: Compiling MetaProcessor.cpp for Release+Asserts build
llvm[4]: Compiling DeclCollector.cpp for Release+Asserts build
llvm[4]: Compiling MetaSema.cpp for Release+Asserts build
In file included from /home/alex/ec/build/cling-src/tools/cling/lib/Interpreter/DeclCollector.cpp:10:
/home/alex/ec/build/cling-src/tools/cling/lib/Interpreter/DeclCollector.h:132:18: warning: 
      'cling::DeclCollector::HandleVTable' hides overloaded virtual function [-Woverloaded-virtual]
    virtual void HandleVTable(clang::CXXRecordDecl* RD);
                 ^
/home/alex/ec/build/cling-src/tools/cling/lib/Interpreter/../../../clang/include/clang/AST/ASTConsumer.h:136:16: note: 
      hidden overloaded virtual function 'clang::ASTConsumer::HandleVTable' declared here: different number of
      parameters (2 vs 1)
  virtual void HandleVTable(CXXRecordDecl *RD, bool DefinitionRequired) {}
               ^
llvm[4]: Compiling DeclExtractor.cpp for Release+Asserts build
/home/alex/ec/build/cling-src/tools/cling/lib/Interpreter/DeclCollector.cpp:201:19: error: no member named
      'HandleInvalidTagDeclDefinition' in 'clang::ASTConsumer'; did you mean 'HandleTagDeclDefinition'?
      m_Consumer->HandleInvalidTagDeclDefinition(TD);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  HandleTagDeclDefinition
/home/alex/ec/build/cling-src/tools/cling/lib/Interpreter/../../../clang/include/clang/AST/ASTConsumer.h:75:16: note: 
      'HandleTagDeclDefinition' declared here
  virtual void HandleTagDeclDefinition(TagDecl *D) {}
               ^
/home/alex/ec/build/cling-src/tools/cling/lib/Interpreter/DeclCollector.cpp:212:34: error: too few arguments to
      function call, expected 2, have 1
      m_Consumer->HandleVTable(RD);
      ~~~~~~~~~~~~~~~~~~~~~~~~   ^
/home/alex/ec/build/cling-src/tools/cling/lib/Interpreter/../../../clang/include/clang/AST/ASTConsumer.h:136:3: note: 
      'HandleVTable' declared here
  virtual void HandleVTable(CXXRecordDecl *RD, bool DefinitionRequired) {}
  ^
1 warning and 2 errors generated.
make[4]: *** [/home/alex/ec/build/builddir/tools/cling/lib/Interpreter/Release+Asserts/DeclCollector.o] Error 1
make[4]: *** Waiting for unfinished jobs....
llvm[4]: Building Release+Asserts Archive Library libclingMetaProcessor.a
make[4]: Leaving directory `/home/alex/ec/build/builddir/tools/cling/lib/MetaProcessor'
make[4]: Leaving directory `/home/alex/ec/build/builddir/tools/cling/lib/Interpreter'
make[3]: *** [Interpreter/.makeall] Error 2
make[3]: Leaving directory `/home/alex/ec/build/builddir/tools/cling/lib'
make[2]: *** [all] Error 1
make[2]: Leaving directory `/home/alex/ec/build/builddir/tools/cling'
make[1]: *** [all] Error 1
make[1]: Leaving directory `/home/alex/ec/build/builddir/tools'
make: *** [all] Error 1
subprocess.CalledProcessError: Command 'make -j4' returned non-zero exit status 2



┌──────────────────────────────────────────────────────────────────────────────┐
│ Clean up                                                                     │
└──────────────────────────────────────────────────────────────────────────────┘
Remove directory: /home/alex/ec/build/builddir
Remove directory: /tmp/cling-obj/
Create output directory: /home/alex/ec/build/cling-0.2~dev-bb7b609-1
````

And I have below gcc and llvm installed
````bash
gcc version 4.8.5
llvm-3.9
clang-3.9
````

**Comment by karies** [comment]
This works outside cpt.py...

**Comment by vgvassilev** [comment]
Should be fixed. Please reopen if there is still an issue.
