### ISSUE TITLE
Jupyter kernel : error in decoding utf8 at notebook start

### ISSUE THREAD

**Issue by nivoliev** [root-mirror/cling#9]
When evaluating the first cell of a notebook, I get the following error:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/clingkernel.py", line 159, in publish_pipe_output
    data = self._recv_dict(self.output_pipe)
  File "/usr/lib/python3.5/site-packages/clingkernel.py", line 132, in _recv_dict
    value = os.read(pipe, len_value).decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 18: invalid continuation byte
```

The error only occurs when evaluating the first cell, the other cells do not show the message afterwards. Trying to dig a bit, modifying the code where the exception occurs as:

```python
    def _recv_dict(self, pipe):
        """Receive a serialized dict on a pipe
        
        Returns the dictionary.
        """
        # Wire format:
        #   // Pipe sees (all numbers are longs, except for the first):
        #   // - num bytes in a long (sent as a single unsigned char!)
        #   // - num elements of the MIME dictionary; Jupyter selects one to display.
        #   // For each MIME dictionary element:
        #   //   - length of MIME type key
        #   //   - MIME type key
        #   //   - size of MIME data buffer (including the terminating 0 for
        #   //     0-terminated strings)
        #   //   - MIME data buffer
        data = {}
        b1 = os.read(pipe, 1)
        sizeof_long = struct.unpack('B', b1)[0]
        if sizeof_long == 8:
            fmt = 'Q'
        else:
            fmt = 'L'
        buf = os.read(pipe, sizeof_long)
        num_elements = struct.unpack(fmt, buf)[0]
        for i in range(num_elements):
            buf = os.read(pipe, sizeof_long)
            len_key = struct.unpack(fmt, buf)[0]
            key = os.read(pipe, len_key).decode('utf8')
            buf = os.read(pipe, sizeof_long)
            len_value = struct.unpack(fmt, buf)[0]
            #value = os.read(pipe, len_value).decode('utf8')
            #data[key] = value
            try:
                buf = os.read(pipe, len_value)
                value = buf.decode('utf8')
                data[key] = value
                break
            except :
                value = buf.decode('utf8','replace')
                self.session.send(self.iopub_socket, 'display_data',
                    content={
                        'data':{
                            key:"error reading value : %d/%d %s : %d %s" %(i, num_elements, key, len_value, value),
                        },
                        'metadata':{},
                    },
                    parent=self._parent_header,
                )
                raise
        return data
```
I have the following output in the notebook:

```
error reading value : 0/1 text/html : 7168 [<garbage characters>]
```

The garbage characters vary from run to run, but the other fields keep their value. It seems to me that when the kernel starts, the initial data sent to the pipe cannot be read properly. If I remove the `raise`, the message appears at each cell evaluation.

I installed jupyter and cling through [archlinux user repository](https://aur.archlinux.org/packages/cling-jupyter-git/). Removing line 124 from `tools/Jupyter/Kernel.cpp`:

```C++
cling::Jupyter::pushOutput({{"text/html", "You just executed C++ code!"}});
```

It seems that I no longer have the error.

**Comment by karies** [comment]
Yeah that output was more of a built-in feature test ;-) Removed in the master.

I believe that there is still an issue with an out-of-sync message going over the wire, though, so don't hesitate to open another issue if you see this again.
